### ISSUE TITLE
No notifications sounding through Android

### ISSUE THREAD

**Issue by lordvic1001** [balzack/databag#112]
The app recently stopped notifying of new messages on at least Android phones. I'm running app version 1.5 with latest android 14 updates.

**Comment by balzack** [comment]
It appears google has deprecated the API I was using for delivering push notifications to Android phones. This will likely take me a few days to sort out and require an updated server container. I'm sorry for the outage :(

**Comment by balzack** [comment]
If you get a chance, can you update the the latest container and test it out; this should now be resolved. Thank you for reporting this!

**Comment by lordvic1001** [comment]
I have updated to the latest container, along with a friend who regularly chats with me via Databag. He is receiving notifications now, but I am not. 

Friend's Phone: Galaxy S21 5G - SM-G991U1 Kernel Version 5.4.254-qgki-28582291-abG991U1UEUCFXGB running Android 14
My Phone: Pixel 6 with the Jun 20th 2024 Databag Update installed

**Comment by lordvic1001** [comment]
Any ideas on why myself and clients of my server specifically are still not receiving notifications?

**Comment by balzack** [comment]
Sorry, somehow I missed your last message. 

With the firebase API changes, I now need to host a "repeater" to channel the push notifications through the firebase SDK. Do you have any firewall settings that would prevent communication to: https://repeater.coredb.org/notify?

Would you be able to look at the container logs when you write a message that should produce a push notification, and see if any errors appear?

I'm sorry for the difficulties.

**Comment by lordvic1001** [comment]
I'll need some guidance on how to do that. I should have on e way communication enabled out from my server to your repeater, but i'll explicitly allow it.

**Comment by balzack** [comment]
I am happy to help. Assuming your are using a container, the logs should be printed as the container output. If you have trouble viewing the container output, let me know what you use for hosting and I will try and figure it out.

**Comment by lordvic1001** [comment]
[dblog.txt](https://github.com/user-attachments/files/17301393/dblog.txt)
Here's the log.

**Comment by balzack** [comment]
I am a bit at a loss, I don't see anything wrong with your server from the logs.

Can you test with the demo server (databag.coredb.org)? Create an account and login with the mobile app; then see if you can create a push notification from another account?

**Comment by lordvic1001** [comment]
I'll try that out.

Sent with [Proton Mail](https://proton.me/mail/home) secure email.

**Comment by VlaK0r** [comment]
Hello friends! 
I have the same problems only on a Huawei smartphone.

**Comment by balzack** [comment]
@VlaK0r you are able to get notifications on other phones but not the Huawei? Is it just sound that is not working?

**Comment by VlaK0r** [comment]
@balzack It is notifications that do not come.

**Comment by VlaK0r** [comment]
@balzack Everything works for my wife on the iPhone.

**Comment by balzack** [comment]
Hrm, I know this has been reported before, but I can't reproduce this on my pixel/android phone. Is there anything special about the firmware on your phone. LineageOS for example?

**Comment by VlaK0r** [comment]
@balzack I installed it for the first time. "Microg" is installed on the smartphone so that there would be support for Google services, including notifications.

**Comment by lordvic1001** [comment]
All, I still need to test this.

Sent with [Proton Mail](https://proton.me/mail/home) secure email.

**Comment by lordvic1001** [comment]
Ok, i had a friend set an account up for me on his server and i'm receiving notifications successfully. It's my own server that is not sending notifications for some reason. We're going to re-attempt from my server now.

**Comment by on9686** [comment]
I have the same problems only my phone.

My phone : Galaxy S23 (SM-S911N) in Android 14.
Friend's phone : Galaxy S21 (SM-S991N) in Android 14.

I couldn't get the notification when I installed the apk released from obtanium, and when reinstalled via Google Play, I received the notification fine.

**Comment by lordvic1001** [comment]
Alright Balzack,

I connected my app to my friend's server with a local account on his server. This restored my notifications somehow. I then had one of my users uninstall the phone application completely and re-install it. This resolved his notifications via my server. I also reconnected my phone application to my own-server and the notifications were still consistently notifying me of new messages. Is there a field within the phone application that's not getting updated? My issue is resolved now, so this thread can be closed out on my end.

**Comment by balzack** [comment]
@on9686 , I am not sure where the APK from obtanium came from. If it came from the fdroid store, then it would not have push notifications working through google. The fdroid build has it removed as the supporting libraries are not open source. Do you know if this is the case?

**Comment by balzack** [comment]
@lordvic1001 there is a switch in account settings that enables/disables push notifications. Initially I had that default off, recently I had it default on. Perhaps that was the source of the issue?

**Comment by on9686** [comment]
@balzack I found obtanium's APK came from github released APK file, so it was old version(1.1.11, Nov 8 2023). For now, I'm just going to use the Google Play version. Thank you for your response.

**Comment by lordvic1001** [comment]
My switch was never turned off.

Sent with [Proton Mail](https://proton.me/mail/home) secure email.
